[project]
name = "BakerPy"
requires-python = ">=3.12"
version = "0.0.0"
dependencies = [
  "cookiecutter"
]

[tool.ruff]
line-length = 75
exclude = ["templates"]

[tool.ruff.lint]
select = ["I", "E4", "E7", "E9", "Q", "F"]

[dependency-groups]
dev = [
  "pytest",
  "ruff",
  "pre-commit"
]
