name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install uv
        uv sync
    - name: Test with pytest
      if: success()
      run: |
        source .venv/bin/activate
        echo "Running tests with pytest"
        pytest tests
    - name: Ruff Check
      if: success()
      run: |
        source .venv/bin/activate
        echo "Linting check with ruff"
        ruff check
